import type { Metadata } from 'next';
import ThemeProvider from '../context/ThemeProvider';
import TopNav from '../components/nav/TopNav';
import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import { BusinessProvider } from '@/context/business';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

// app/layout.tsx
export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang="en" suppressHydrationWarning>
				<head>
					<script
						dangerouslySetInnerHTML={{
							__html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme');
                  var supportDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches === true;
                  if (theme === 'dark' || (!theme && supportDarkMode)) {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch (e) {}
              })();
            `,
						}}
					/>
				</head>
				<body className="bg-background text-foreground transition-colors duration-300">
					<BusinessProvider>
						<ThemeProvider>
							<TopNav />
							{children}
						</ThemeProvider>
					</BusinessProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
